version: '3.7'

services:
  web1:
    container_name: web1
    build:
      context: .
      target: production
    environment:
      PORT: 3001
    ports:
      - 3001:3001
  web2:
    container_name: web2
    image: nestjs_web1
    environment:
      PORT: 3002
    ports:
      - 3002:3002
